name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install adn Build
      run: |
        npm install --force
        npm run build

    - name: Deploy to Server  # 使用别人包装好的步骤，推送文件模块到远程服务器
      uses: AEnterprise/rsync-deploy@v1.0  
      env:
          DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}   #  远程连接的ssh秘钥，引用配置
          ARGS: -avz --delete                       # rsync参数
          SERVER_PORT: '22'                         # ssh端口
          FOLDER: ./dist                            # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.REMOTE_HOST }}     # 远程连接的host，引用配置
          USERNAME: root                            # 远程连接的用户名，引用配置
          SERVER_DESTINATION: /www/wwwroot/company  # 部署到目标文件的路径

                        